### PR TITLE
fix: attiny84 ADCSRA should be read-write

### PR DESCRIPTION
**Pull request by pitaj**
Haven't found any other variants which are affected by this, but it may be worth pulling all of the access-related patches into common or creating a common/tiny/adc patch.

### CODE REVIEW

**Comment by Rahix** [comment]
Thanks for the PR!

cc @couchand, what do you think about this?  Should we (or even can we) extract a common patch here?

**Comment by couchand** [comment]
I'm constantly amazed by the inconsistency in these ATDFs.

@pitaj Thanks for identifying this and taking care of it!

@Rahix I think the thing to do is remove the mux bits from patch/common/adc.yaml, since the prescaler enum seems consistent across devices and applying the read-write constraint even when it's not needed is harmless.  Then everything can use the common ADC patch, and the places it's being used now just need to define their mux variants.

**Comment by couchand** [comment]
I'd be happy to take care of that refactor after this merges, or @pitaj if you feel like taking that on go ahead.  The usual way to verify a change like that is to back up the old patched directory and then diff it against the new one to make sure the patch refactor is clean.

**Comment by pitaj** [comment]
Any idea when this fix will be released?

**Comment by Rahix** [comment]
Right, next time nag me earlier about this!  I'll see whether I can get a few more things done today/tomorrow; if not I'll just do a release of the current state. :)

**Comment by Rahix** [comment]
@pitaj, I released version 0.2.3 with this fix included just now :)

**Pull request merged**
