### PR TITLE
Add support for attiny828

### PR DESCRIPTION
**Pull request by SnakeOilSalesman**
Adding support for ATtiny828.

Few notes on this:
1. Original `atdf` file had no GPIO `signals` and `pinout` sections. As I understand, pins can be constructed in `avr-hal` even without those sections, but my gut feeling tells me it's better to have them.
2. Previous versions of `atdf` file had register named `EEAR`, which actually, according to the datasheet, is `EEARL`. Latest `atdf` have both - `EEAR` and `EEARL`, but if we keep both of them, `avr-hal` is not able to construct EEPROM. So I decdide to remove `EEAR` variant.

### CODE REVIEW

**Comment by SnakeOilSalesman** [comment]
@Rahix, hey!
May I ask you kindly to take a look into this PR?

**Comment by SnakeOilSalesman** [comment]
@Rahix, is there anything wrong with this PR?
It's been more than 2 month since I opened it and you usually react in 2 days.
I also prepared changes for avr-hal project, but they blocked by this PR.

**Comment by SnakeOilSalesman** [comment]
Hey!

Thanks for reaching out! And sorry for pushing.

I read your comments, thanks for pointing it all out. I'll take another round and will try to do all that stuff with original ATDF file.
Will come back soon.

**Comment by SnakeOilSalesman** [comment]
@Rahix, hey!

Pardon me for a long delay with the update on this one.
I revert ATDF file to the original condition and remove EEAR register via patch file.

Please, let me know, if I missed something.

**Review by Rahix — APPROVED** [review]
Looking great, thanks so much!

**Pull request merged**
