### PR TITLE
Add support for ATtiny816

### PR DESCRIPTION
**Pull request by finga**
Add basic support for the ATtiny816 of the tinyAVR1-series.

### CODE REVIEW

**Review by Rahix — APPROVED** [review]
Looks good to me, any reason you still have the PR marked as draft?  If not, I'd be willing to merge it as is - if more patches are necessary, we can always add them in the future.

**Comment by finga** [comment]
Great!
No specific reason, I just forgot to change the draft state.

**Comment by Rahix** [comment]
Thanks!

**Comment by finga** [comment]
Thank you ;)

**Pull request merged**
